### ISSUE TITLE
Bulk import pdf library: check if exists

### ISSUE THREAD

**Issue by bairhys** [mrmn2/PdfDing#10]
Hi @mrmn2, I tested the [bulk import function](https://codeberg.org/mrmn/PdfDing/issues/78) and it is excellent, a lot easier to import! Thanks for adding it! 

A nice to have minor addition would be if an uploaded PDF already exists, it shows the user and skips uploading it. At the moment, it looks like it appends a string to the filename of uploaded duplicate. The appended string does make it easier to identify duplicates to delete though.

Off topic but I also tested [inverted colours](https://codeberg.org/mrmn/PdfDing/issues/84) and that works great too!

**Comment by mrmn2** [comment]
Hi @bairhys , thanks for the testing. Informing the user about skipped file might be a bit harder to implement. Would it work to add an option to skip files if a file with the same name already exists?

**Comment by bairhys** [comment]
Yeah I think a skip matching filenames option would work great

**Comment by mrmn2** [comment]
I thought about it, I will check for the file name and file size. That way the chance for false positives will be way smaller.

**Comment by bairhys** [comment]
Works great for me! 👍
