### ISSUE TITLE
Show reading progress in PDF list

### ISSUE THREAD

**Issue by bairhys** [mrmn2/PdfDing#11]
A nice to have feature would be to show reading progress on the PDF list. Maybe a percentage and a page count e.g. 10% (10 of 100)

**Comment by mrmn2** [comment]
That's a nice idea. I will work on this right away.

**Comment by bairhys** [comment]
This is nice! Great job 👍 

For 90% of my PDFs it works great but I do seem to have a couple of a PDFs that PdfDing counts 1 page total for some reason. This results in a 100% reading progress, for example: 

```
Progress 100% - Page 16 of 1 
```

**Comment by mrmn2** [comment]
Determining the number of pages is done with this python code snippet:
```
try:
    reader = PdfReader(pdf.file.path)
    pdf.number_of_pages = len(reader.pages)
    pdf.save()
except:  # nosec # noqa
    pass
```

I have set the default number of pages to `1`. That means in case of an error while reading the pdf file via python the number of pages stays at `1`. Note that the current number of pages is done via javascript in the frontend and not in the backend. That is why you get 16 of 1 for example. The reason for doing this was otherwise the progress can only be shown after a file has been opened.

On my end all pdf files did work, so I never encountered the problem before. Could you attach a file, that is not working to your next comment? I'll use this file for investigating.  

I think it should be possible to add the functionality to fix this by setting the number of pages via JS for these cases. Progress bars will only be shown if number of pages has been determined. So for 90% of the files it will be the same behavior as now. For the 10% progress bars will be shown after the file was opened for the first time. If for some reason there are files where both approaches do not work than progress bars will remain missing.

**Comment by mrmn2** [comment]
@bairhys I have just released version 0.6.2. I did a slight refactoring when determining the number of pages in a PDF. Maybe we can already see improvements with your problems.

While refactoring I also added logs when extracting the number of pages in a PDF does not work. Could you set the env variable `LOG_LEVEL`  to `INFO` before updating the container tag? (It would be best to get the logs of the migrations) If there are any problems please make a comment with the logs. Thanks!

**Comment by bairhys** [comment]
@mrmn2 Thanks for your work on this. The default behavior is better now when the number of pages does not work, the progress bars are hidden. And pages read starts from 0 now. 

I found that PDFs can be fixed so PdfFing can determine the total page count. If I download these pdfs and open in Chome, use the Print > Save As PDF feature, then upload file to PdfFing, the total page count is now correct.

But overall great feature addition!

I updated to 0.6.2 with logs set to info and the logs look like this:

```sh
:~$ docker logs pdfding
Operations to perform:
  Apply all migrations: account, auth, contenttypes, pdf, sessions, socialaccount, users
Running migrations:
  Applying pdf.0008_tmp_remove_number_of_pages... OK
Ignoring wrong pointing object 2290 0 (offset 0)
CAUTION: startxref found while searching for %%EOF. The file might be truncated and some data might not be read.
EOF marker not found
Could not determine number of pages for "*****1" of user "bairhys"
Traceback (most recent call last):
  File "/home/nonroot/pdfding/pdf/service.py", line 169, in set_number_of_pages
    reader = PdfReader(pdf.file.path)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.venv/lib/python3.12/site-packages/pypdf/_reader.py", line 133, in __init__
    self._initialize_stream(stream)
  File "/home/nonroot/.venv/lib/python3.12/site-packages/pypdf/_reader.py", line 155, in _initialize_stream
    self.read(stream)
  File "/home/nonroot/.venv/lib/python3.12/site-packages/pypdf/_reader.py", line 608, in read
    self._find_eof_marker(stream)
  File "/home/nonroot/.venv/lib/python3.12/site-packages/pypdf/_reader.py", line 716, in _find_eof_marker
    line = read_previous_line(stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.venv/lib/python3.12/site-packages/pypdf/_utils.py", line 288, in read_previous_line
    raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
pypdf.errors.PdfStreamError: Stream has ended unexpectedly

Ignoring wrong pointing object 2290 0 (offset 0)
CAUTION: startxref found while searching for %%EOF. The file might be truncated and some data might not be read.
EOF marker not found
Could not determine number of pages for "*****2" of user "bairhys"
Traceback (most recent call last):
  File "/home/nonroot/pdfding/pdf/service.py", line 169, in set_number_of_pages
    reader = PdfReader(pdf.file.path)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.venv/lib/python3.12/site-packages/pypdf/_reader.py", line 133, in __init__
    self._initialize_stream(stream)
  File "/home/nonroot/.venv/lib/python3.12/site-packages/pypdf/_reader.py", line 155, in _initialize_stream
    self.read(stream)
  File "/home/nonroot/.venv/lib/python3.12/site-packages/pypdf/_reader.py", line 608, in read
    self._find_eof_marker(stream)
  File "/home/nonroot/.venv/lib/python3.12/site-packages/pypdf/_reader.py", line 716, in _find_eof_marker
    line = read_previous_line(stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nonroot/.venv/lib/python3.12/site-packages/pypdf/_utils.py", line 288, in read_previous_line
    raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
pypdf.errors.PdfStreamError: Stream has ended unexpectedly

  Applying pdf.0009_readd_number_of_pages_with_new_default... OK
Cleaning up shared PDFs with a deletion date in the past.
```

**Comment by mrmn2** [comment]
@bairhys Thanks for testing! There is something not 100% right with the PDF files in question and `pypdf` can therefore not determine the number of pages. If you don't mind your print PDF work around, I would keep it as it is for the time being as using JS when `pypdf` encounters a problem would add some complexity I would like to avoid.

**Comment by bairhys** [comment]
Fair enough, printing to PDF for a couple PDFs is ok
