### ISSUE TITLE
Add highlighting and/or annotations

### ISSUE THREAD

**Issue by dominik-warch** [mrmn2/PdfDing#20]
I'm a fan of a simple, web-based PDF reader! A game changer for me would be if I could highlight text (preferably in 3-4 different colors) and create and save my own annotations (as text or write/free form drawing with a stylus). There is no simple software solution providing this feature without bringing a whole complex other stuff no one needs on top!

**Comment by Zymonick** [comment]
# that would be a key feature for me aswell
