### ISSUE TITLE
Consume Folder

### ISSUE THREAD

**Issue by deuts** [mrmn2/PdfDing#26]
I would really love to see a consume folder for this project -- pretty much like Paperless where you drop documents in a `consume` folder, the app processes them like it would for uploaded files, and probably assign tags according to its settings.

**Comment by mrmn2** [comment]
Could you share some details for your use case? Would a Rest API, which is already planned, also work for automation? Or is the consume folder central to your workflow?

One minor difficulty compared to paperless is that PdfDing has multiple users. I think paperless only has one. I could work around that by using the IDs of the users, so the directory `consume/1` would be for files belonging to user `1`. 

How do you envision assigning tags for PDFs create via the consume folder would work?

**Comment by deuts** [comment]
Hi @mrmn2 thank you for the response.

My current workflow with Paperless and its consume folder involves: I have an Android document scanner app (Genius Scan) and I have my documents saved to the local folder in the Android system after scanning. That folder is being watched by Resilio Sync, which it syncs to the Paperless consume folder. Once Paperless successfully imports that document, it is removed from the Consume folder, which is removed as well from my local folder in Android by virtue of Resilio Sync.

So I guess this is different from the Rest API?

**Comment by deuts** [comment]
> Thank you for the response. Yes this use case will not work with a rest API. I'll implement the consume folder.

Thanks. Appreciate your efforts.

**Comment by mrmn2** [comment]
@deuts I have just released version 0.7.0 which includes this feature. You will find the information necessary for configuring this feature [here](https://github.com/mrmn2/PdfDing/blob/master/docs/configuration.md#consumption-directory). Please let me know if it is working :)
