### ISSUE TITLE
The menu bar should be horizontally scrollable on mobile UI

### ISSUE THREAD

**Issue by n00b12345** [mrmn2/PdfDing#37]
The image below is a screenshot from the landscape mode of my mobile.

The whole UI shifts because the menu bar at the top is not able to accommodate all the options. Ideally this should be scrollable.

![Screenshot_20241227_134130_Firefox.jpg](https://github.com/user-attachments/assets/a7f60de1-2423-4744-a70d-3267dfdb2d9f)

By the way, thank you so much for creating PDFDing. I love it!

**Comment by n00b12345** [comment]
Sorry about raising this issue again.

It seems that in portrait mode on mobile too, the menus are a little too wide. I'm not sure if this is a limitation of the library, but it would be great if the navigation menu itself was scrollable.

In the screenshot below, as you can see, the buttons on navigation menu are not visible and the user needs to scrolls horizontally to access the rest. 

 ![Screenshot_20241230_015421_Firefox.jpg](https://github.com/user-attachments/assets/65a80a84-66d6-4256-8034-243cfac3bdcd)

**Comment by mrmn2** [comment]
No worries. With the recent fix this case should be covered as well. 

Please give some feedback if everything works as expected once 0.9.1 will be released in the next few days.
