### ISSUE TITLE
Viewing total number of registered users

### ISSUE THREAD

**Issue by n00b12345** [mrmn2/PdfDing#40]
Ideally, the first user should be set as admin and be able to view total registered users on the application. That way when PDFDing is exposed to the internet, the admin will be able to see if any unwanted users have signed up.

An alternate way of doing this may be to allow the first user to sign up even if "DISABLE_USER_SIGNUP" is set as TRUE. That way the admin is in control of account creation entirely.

**Comment by mrmn2** [comment]
There is actual another way with django which is the framework I am using for PdfDing. You can set `DISABLE_USER_SIGNUP` to `"TRUE"`, enter the shell of the running container, execute `python pdfding/manage.py createsuperuser` and follow the prompt. By doing this you will create an admin user. 

I will add this to the [admin](https://github.com/mrmn2/PdfDing/blob/master/docs/guides.md#admin-users) section of the user guide.

**Comment by n00b12345** [comment]
Just wanted to add that the correct command to enter the bash prompt for PDFding is `docker exec -it <container_id_or_name> /bin/sh` and not `docker exec -it <container_id_or_name> /bin/bash` (a mistake that I was stupidly making).

**Comment by mrmn2** [comment]
Yes because of the underlying alpine image there is no bash shell available. Do you think it is a good idea to add this to the admin guide section?

**Comment by n00b12345** [comment]
> Yes because of the underlying alpine image there is no bash shell available. Do you think it is a good idea to add this to the admin guide section?

I think it's a very good idea to add this to the admin guide. It will help users who are new to self-hosting as well 👍
