### ISSUE TITLE
Hover text over menu items

### ISSUE THREAD

**Issue by n00b12345** [mrmn2/PdfDing#41]
Being able to see what each of these options do when the mouse hovers over them would be very helpful. I understand that it is self-explanatory, but it will definitely improve ease of use for the users.

![Screenshot 2024-12-27 143117](https://github.com/user-attachments/assets/7ea4d429-81e9-459a-9932-38c49bd588b5)

**Comment by mrmn2** [comment]
I agree. Already done, will be part of the next release.
