### ISSUE TITLE
Ability to add shapes

### ISSUE THREAD

**Issue by n00b12345** [mrmn2/PdfDing#45]
The ability to add shapes like circles or reactangles (but especially vertical lines), would be really nice to have. It would help highlight areas and create underlines etc. Please consider it if possible.

**Comment by mrmn2** [comment]
Sadly, this is not possible as of now. Almost all functionality to the PDF viewer is done in the [pdf.js](https://github.com/mozilla/pdf.js) library. This library currently does not have the features you would like to have. If the will be present in a feature release I can add them.
