### ISSUE TITLE
[Feature request] Add author in the metadata

### ISSUE THREAD

**Issue by update-freak** [mrmn2/PdfDing#46]
Hi,

I think it makes sense to add a field for author / authors in the metadata
(also a filter that the pdfs can be searched for author)

**Comment by mrmn2** [comment]
With metadata you mean that there is a field during the PDF creation and that the author will be displayed in the details page, correct?

**Comment by update-freak** [comment]
Yes indeed. A additional field in the details overview of the PDFs

**Comment by mrmn2** [comment]
I thought about it again, I think the author field might not be necessary. PdfDing supports multi-level tags. So you could use the tags `lecture_notes/author1` and `lecture_notes/author2`. You could then list all lecture notes by searching for `#lecture_notes`, or e.g. `#lecture_notes/author1` for only listing the notes related to author1.

**Comment by update-freak** [comment]
yes, this is also a possibility to use tags for that. Thanks.
Feel free to close this feature request
