### ISSUE TITLE
[Feature request] Allow more than one tags for a pdf

### ISSUE THREAD

**Issue by update-freak** [mrmn2/PdfDing#49]
Hi,

it would be good to have the possibility to add multiple tags to one pdf file and not just one tag.

**Comment by mrmn2** [comment]
I am not exactly sure what you mean by this. It is already possible to add multiple tags to a PDF. If you want to have multiple tags, e.g. #tag1 and #tag2, you will need to enter `tag1 tag2` (separated by a space) into the tag input field.

Btw, if you like PdfDing it would be really great if you could give the project a star. Thanks!

**Comment by update-freak** [comment]
Ah ok. Was not aware that this is possible with space.
Thanks a lot.
